apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ochami-helm.fullname" . }}-root-ca
  labels:
    {{- include "ochami-helm.labels" . | nindent 4 }}
data:
  root_ca.crt: "-----BEGIN CERTIFICATE-----MIIBvTCCAWUCEAD42h6/YaN5AUAWnL3+ifcwDQYJKoZIhvcNAQEEBQAwYTELMAkGA1UEBhMCVVMxETAPBgNVBAoTCEV4YW1wbGUgT3JnMSUwIwYDVQQLExxIdXR0ZXIgMTAxIENlcnRpZmljYXRlIEF1dGhvcml0eTELMAkGA1UEAxMCQ0EwHhcNMDMwNDIyMTYwNDM5WhcNMDQwNDIxMTYwNDM5WjBhMQswCQYDVQQGEwJVUzERMA8GA1UEChMIRXhhbXBsZSBPcmcxJTAjBgNVBAsTHEh1dHRlciAxMDEgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQswCQYDVQQDEwJDQTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEApxKcps3s2x4pEw7N3bC52cQd3fCK+wIJJq+j8n8pZTJtN3rffwCeUK7TqcrLp93jeWdD/tEz/mWApRSVvFucEc0jijsvfBEnaG8kE+3hQ31S8ZKgXN4f6DkC2J3fKW/ob/ahOzDY5E2F7p/w/IeQ4fPSxWdlhY4dM05y5a3L3TUCAwEAATANBgkqhkiG9w0BAQQFAAOBgQCKn4/VyZdLA+yDpv9sCe4fW/iqud4E/98gqc21z8D9LgKxPjPyV5aVnS2HXxAmAbT/cQilp2iDBpA4y0AFdCfyKy3Jc5y2YVBCvENyvUXK3gBKyAfr2p4FfX5yqIW4s4d91Jh2eJ9i8Yp21C5fPpxAmZ8m0j3p2Vf4y3XNVjAn2A==-----END CERTIFICATE-----"
