# Default values for ochami-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  smd:
    repository: localhost/smd
    pullPolicy: IfNotPresent
    tag: "local-smd"
  postgres:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "11.5-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ochami"

service:
  smd:
    type: ClusterIP
    port: 27779
  bss:
    type: ClusterIP
    port: 27778
  postgres:
    type: ClusterIP
    port: 5432
  coredhcp:
    type: ClusterIP
    port: 67

postgres:
  user: ochami
  password: "CHANGEME"
  smd_password: "CHANGEME"
  bss_password: "CHANGEME"
  hydra_password: "CHANGEME"

# smdInit job configuration
smdInit:
  image:
    repository: localhost/smd
    tag: "local-smd"
    pullPolicy: IfNotPresent

smd:
  db:
    host: "ochami-postgres"
    port: 5432
    name: "hmsds"
    user: "smd-user"
    opts: "sslmode=disable"
  jwks:
    url: ""

# bssInit job configuration
bssInit:
  image:
    repository: localhost/bss
    tag: "local-bss"
    pullPolicy: IfNotPresent

# coredhcpInit job configuration
coredhcpInit:
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent

coredhcp:
  image:
    repository: localhost/coresmd
    tag: "local-coresmd"
    pullPolicy: IfNotPresent
  server_id: "192.168.0.254"
  dns: "1.1.1.1 8.8.8.8"
  router: "172.16.0.254"
  netmask: "255.255.255.0"
  cache_update_interval: "30s"
  long_lease_time: "1h"
  short_lease_time: "5m"
  bootloop:
    storage_path: "/tmp/coredhcp.db"
    ip_pool_start: "192.168.0.150"
    ip_pool_end: "192.168.0.253"
  # customConfig: |
  #   server4:
  #     ...



bss:
  image:
    repository: localhost/bss
    tag: "local-bss"
    pullPolicy: IfNotPresent
  db:
    host: "ochami-postgres"
    port: 5432
    name: "bssdb"
    user: "bss-user"
    opts: "sslmode=disable"
  jwks:
    #url: "http://ochami-opaal:3333/keys"
    url: ""
  ipxe:
    server: "192.168.100.1"
  chain:
    proto: "http"
  bootscript:
    #notify_url: "http://ochami-tpm-manager:27780/Node"
    notify_url: ""
  advertise_address: "localhost" # without this value, the bss microservice doesn't start

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# HTTP Server configuration
httpServer:
  enabled: true
  image:
    repository: localhost/http-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30080
