# Custom values for PXE boot setup with Minikube on 192.168.100.2
externalIp: "192.168.100.2"
dhcpStart: "192.168.100.100"
dhcpEnd: "192.168.100.200"
dhcpNetmask: "255.255.255.0"

coredhcp:
  customConfig: |
    server4:
      listen: "0.0.0.0:67"
      plugins:
        - server_id: {{ .Values.externalIp }}
        - router: {{ .Values.externalIp }}
        - dns: 8.8.8.8
        - netmask: {{ .Values.dhcpNetmask }}
        - range: /tmp/coredhcp.leases {{ .Values.dhcpStart }} {{ .Values.dhcpEnd }} 1h
        - nbp: "http://{{ .Values.externalIp }}:30080/boot.ipxe"
